- components/Header/Header.tsx
- components/SideNav.tsx
- pages/_app.tsx
- pages/admin/company-membership.tsx
- pages/admin/terms/index.tsx
- pages/index.tsx
- styles/globals.css
> Sidebar & Layout

- components/Header/Header.tsx
- pages/admin/terms/index.tsx
> Design: 약관관리 페이지 디자인 수정

- pages/admin/company-membership.tsx
> Design: 기업 관리 페이지 디자인 수정

- components/ui/Button_1.tsx
- pages/company/notice/[noticeId].tsx
- pages/company/notice/index.tsx
- pages/company/notice/new.tsx
close #18 
페이지 와이어 프레임 마크업: notice, notice/new , notice/1
> feat: notice, notice/new , notice/1 wireframe markup

- components/layout/HeadLayout.tsx
- components/layout/SNBLayout.tsx
- pages/_app.tsx
- pages/admin/terms/index.tsx
> Design: body 영역 100vh로 변경

- components/SideNav.tsx
- pages/admin/terms/[termsId].tsx
- pages/admin/terms/index.tsx
- pages/company/applicant-management.tsx
- styles/globals.css
#4 약관페이지
- 최종 약관 페이지
- 약관별 페이지
- 약관별 페이지로 이동 기능 추가
> Feat: 약관 페이지

- components/SideNav.tsx
- pages/_app.tsx
- pages/_document.tsx
- 파비콘, 타이틀 작성하는 Head 코드 document에서 app으로 옮김
> Fix: Head 코드 수정

- components/company/job-posting/PostCard.tsx
- components/company/notification/MailCells.tsx
- pages/company/applicant-management/category/[categoryId].tsx
- pages/company/applicant-management/index.tsx
- pages/company/job-posting/index.tsx
- pages/company/notification.tsx
> Feat: company/job-posting page

- .prettierrc
- components/company/job-posting/PostCard.tsx
- components/company/notification/MailCells.tsx
- components/ui/Button_2.tsx
- pages/company/job-posting/index.tsx
- pages/company/notification.tsx
> Update: .prettier

- components/ui/Card_1.tsx
- libs/client/axiosClient.ts
- libs/hooks/useAccessToken.ts
- package-lock.json
- package.json
- pages/company/index.tsx
- pages/company/job-posting/new.tsx
- pages/company/notification.tsx
- pages/login.tsx
- types.d.ts
> Feat: Card_1.tsx

- __test__/axios.test.ts
- libs/client/axiosClient.ts
- pages/api/notice/index.ts
- pages/company/job-posting/index.tsx
- pages/login.tsx
- types.d.ts
> Test: axiosClient.ts & Update: types.d.ts

- libs/client/axiosClient.ts
- pages/login.tsx
- types.d.ts
> Add: Notice api codes in axiosClient.ts

- components/AccordionMenu.tsx
- components/SideNav.tsx
- pages/company/applicant-management/index.tsx
- tsconfig.json
> Feat: company/applicant-management 표디자인

- components/AccordionMenu.tsx
> Fix: SubNavbar styling

- components/SideNav.tsx
- components/ui/Card_1.tsx
- pages/company/index.tsx
- pages/company/notification.tsx
> Feat: 사이드메뉴에서 토큰복사하기

- components/SideNav.tsx
- pages/admin/terms/[termsId].tsx
- pages/admin/terms/detail/[termsId].tsx
- pages/admin/terms/new.tsx
- types.d.ts
- 약관페이지
- 로그아웃 버튼
build 에러가나서 test 브랜치 만들었습니다.
> feat: 약관페이지, 로그아웃 버튼

- libs/client/axiosClient.ts
- pages/admin/company-membership/[companyId].tsx
- pages/admin/terms/[termsId].tsx
- pages/admin/terms/detail/[termsId].tsx
- pages/admin/terms/index.tsx
- 약관 기능 중 필요없는 콘솔로그 코드 삭제
- 약관 삭제 버튼 위치 이동(약관목록 -> 약관 상세페이지)
- 삭제기능 구현 완료
> delete: 약관 기능 필요없는 콘솔로그 삭제

- libs/hooks/useCookies.ts
- pages/community/faq/[faqId].tsx
- pages/community/faq/index.tsx
- pages/community/notice/[noticeId].tsx
- pages/community/notice/edit/[noticeId].tsx
- pages/community/notice/index.tsx
> Feat: isAdmin에 따라 display: none

- libs/client/axiosClient.ts
- pages/admin/terms/[termsId].tsx
- pages/admin/terms/detail/[termsId].tsx
- types.d.ts
- 약관 상태 변경 기능
- 약관 상태 변경하고 바로 업데이트 되지않는 문제가 있음 (해결 예정)
> feat: 약관 상태 변경 기능

- components/SideNav.tsx
- components/company/job-posting/MailModal.tsx
> Update: SNB 메뉴 몇개 삭제

- components/company/job-posting/AddModal.tsx
- libs/utils.ts
- pages/company/job-posting/[recruiting_id].tsx
- pages/company/job-posting/index.tsx
> Feat: 공고올리기 기능

- components/ui/SelectCategory.tsx
- pages/community/faq/[faqId]/[category]/edit.tsx
- pages/community/faq/[faqId]/[category]/index.tsx
- pages/community/faq/index.tsx
- pages/community/notice/[noticeId].tsx
- pages/community/notice/edit/[noticeId].tsx
- pages/community/notice/index.tsx
- faq 카테고리 안나오는 부분 아무래도 거슬려서 고치다 보니 파일 구조까지 바껴버렸습니다.
- 시간 표시 부분도 slice추가
- 리스트 출력할 때 전체  width가 잘려서 나오는 부분 수정
> Feat: faq category next/link query이용

- components/community/FaqAddModal.tsx
- components/community/NoticeAddModal.tsx
usestate 를 textarea에 쓴 부분이 계속 거슬렸는데 
console.log 찍어보니 리랜더링이 정말 많이 일어나는 것을 발견해서 useRef로 바꿨습니다.
> Feat: useState, useRef로 대체
